"""add leadermeeting created_at index

Revision ID: 62f954a26b34
Revises: 46cbdc373e79
Create Date: 2026-03-12 22:02:43.382695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f954a26b34'
down_revision: Union[str, Sequence[str], None] = '46cbdc373e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_leader_meetings_created_at'), 'leader_meetings', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leader_meetings_created_at'), table_name='leader_meetings')
    # ### end Alembic commands ###
